apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-goem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-goem
    app.kubernetes.io/part-of: tkwch-fix-0075-0028-app
  name: devfile-sample-goem
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-goem
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-goem
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0028-tenant/tkwch-fix-0075-0028-app/devfile-sample-goem@sha256:867c240d7fd29f5c760fdd2860dbd185a3070131e94703cf2ad965eac45939f1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
